# Generated by Django 4.1.3 on 2023-10-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_client_client_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[
                    ("Not Contacted", "Not Contacted"),
                    ("Initiated", "Initiated"),
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                    ("Rejected", "Rejected"),
                ],
                default="Not Contacted",
                max_length=100,
            ),
        ),
    ]
